//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYN.BLOG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalLink
    {
        public int Id { get; set; }
        public string LinkName { get; set; }
        public string LinkURL { get; set; }
        public short Status { get; set; }
        public System.DateTime SubTime { get; set; }
        public Nullable<System.DateTime> AltTime { get; set; }
    }
}
