//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYN.BLOG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticFile
    {
        public int Id { get; set; }
        public string FileRawName { get; set; }
        public string FileNowName { get; set; }
        public string FileLocalPath { get; set; }
        public string FileOnLineURL { get; set; }
        public Nullable<int> FromArticleId { get; set; }
        public short FileType { get; set; }
        public System.DateTime UploadTime { get; set; }
    }
}
