//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYN.BLOG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public Visitor()
        {
            this.Comments = new HashSet<Comment>();
            this.LeaveMsgs = new HashSet<LeaveMsg>();
        }
    
        public int Id { get; set; }
        public string VisitorName { get; set; }
        public Nullable<int> VisitorIconId { get; set; }
        public string VisitorEmail { get; set; }
        public string VisitorQQ { get; set; }
        public short Status { get; set; }
        public System.DateTime SubTime { get; set; }
        public Nullable<System.DateTime> AltTime { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual HeadIcon HeadIcon { get; set; }
        public virtual ICollection<LeaveMsg> LeaveMsgs { get; set; }
    }
}
